import React from 'react';
import {View, ScrollView} from 'react-native';
import Text from '../../components/Text';
import _ from 'underscore';
import styles from '../../styles/styles';
import themeColors from '../../styles/themes/default';
import HeaderWithBackButton from '../../components/HeaderWithBackButton';
import ScreenWrapper from '../../components/ScreenWrapper';
import withLocalize from '../../components/withLocalize';
import * as GetAssistance from '../../libs/actions/GetAssistance';
import Navigation from '../../libs/Navigation/Navigation';
import Button from '../../components/Button';
import FixedFooter from '../../components/FixedFooter';
import * as Expensicons from '../../components/Icon/Expensicons';
import * as Illustrations from '../../components/Icon/Illustrations';
import withWindowDimensions from '../../components/withWindowDimensions';
import * as Validation from '../../libs/Validation';
import * as API from '../../libs/API';
import * as Report from '../../libs/actions/Report';
import * as ReportUtils from '../../libs/ReportUtils';
import * as User from '../../libs/actions/User';
import * as Link from '../../components/Link';
import * as OptionsList from '../../libs/OptionsList';
import * as OptionsListUtils from '../../libs/OptionsListUtils';
import * as Policy from '../../libs/actions/Policy';
import * as PolicyUtils from '../../libs/PolicyUtils';
import * as ReportActions from '../../libs/actions/ReportActions';
import * as ReportAction from '../../libs/actions/ReportAction';
import * as ReportActionComposeView from '../../components/ReportActionItem/ReportActionItem';
import * as ReportActionItem from '../../components/ReportActionItem';
import * as ReportActionItemPropTypes from '../../components/ReportActionItem/ReportActionItem';
import * as ReportActionItemFragment from '../../components/ReportActionItemFragment';
import * as ReportActionItemFragmentPropTypes from '../../components/ReportActionItemFragment/ReportActionItemFragment';
import * as ReportActionItemDate from '../../components/ReportActionItemDate';
import * as ReportActionItemMessage from '../../components/ReportActionItemMessage';
import * toLocalCurrency from '../../libs/Currency';
import toLocaleHeading from '../../libs/NumberFormat';
import toLocalPhone from '../../libs/LocalePhoneNumber';
import toLocalTime from '../../libs/DateUtils';
import toLocaleDate from '../../libs/DateUtils';
import toLocaleTime from '../../libs/DateUtils';
import toLocaleOrdinal from '../../libs/NumberFormat';
import toLocaleAmount from '../../libs/Currency';
import toLocaleRoom from '../../components/RoomNameInput';
import toLocaleUser from '../../components/UserDetailsTooltip';
import toLocaleRoom from '../../components/RoomNameInput';
import toLocaleUser from '../../components/UserDetailsTooltip';