import React, {Component} from 'react';
import {View} from 'react-native';
import {withOnyx} from 'react-native-onyx';
import _ from 'underscore';
import PropTypes from 'prop-types';
import styles from '../../styles/styles';
import withLocalize, {withLocalizePropTypes} from '../../components/withLocalize';
import * as ValidationUtils from '../../libs/ValidationUtils';
import * as LoginUtils from '../../libs/LoginUtils';
import {View, Text, Button} from 'react-native';
import {withNavigation} from '@react-navigation/compat';
import {withNavigationFocus} from '@react-navigation/native';
import {withNetwork} from '../../components/OnyxProvider';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as Validation from '../../libs/actions/Validation';
import {withOnyx} from 'react-native-onyx';
import withWindowDimensions from '../../components/withWindowDimensions';
import compose from '../../libs/compose';
import {withNetwork} from '../../components/OnyxProvider';
import * as Device from '../../libs/actions/Device';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as Validation from '../../libs/actions/Validation';
import * as LoginUtils from '../../libs/LoginUtils';
import * as OptionsListUtils from '../../libs/OptionsListUtils';
import * as PersonalDetails from '../../libs/PersonalDetails';
import * as NameValuePair from '../../libs/actions/NameValuePair';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as NetworkConnection from '../../libs/NetworkConnection';
import * * 
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as NetworkConnection from '../../libs/NetworkConnection';
import * as Pusher from '../../libs/Pusher';
import * as Session from '../../libs/actions/Session';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * * * * Session from '../../libs/actions/Session';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * * * * Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * as User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as Pusher from '../../libs/Pusher';
import * as User from '../../libs/actions/User';
import * * * * User from '../../libs/actions/User';
import * as Session from '../../libs/actions/Session';
import * as Push