import React, {useState, useEffect, memo, useMemo} from 'react';
import {View, Text, Pressable} from 'react-native';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';
import {withPersonalDetails} from '../with';
import {withNetwork} from 'react';