import React, {useState, useRef} from 'react';
import {View, Pressable} from 'react-native';
import PropTypes from 'prop-types';
import styles from '../styles/styles';
import themeColors from '../styles/themes/default';
import CONST from '../CONST';
import ThreeDotsMenu from './ThreeDotsMenu';
import Badge from './Badge';
import * as Expensicons from '../components/Icon/Expensicons';
import MenuItemPropTypes from './MenuItemPropTypes';
import useWindowDimensions from '../hooks/useWindowDimensions';
import Navigation from '../libs/Navigation/Navigation';