import React, {useContext, useEffect, useRef} from 'react';
import {View, Pressable, Text, Animated} from 'react-native';
import {withReportActionsDrafts} from '../OnyxProvider';
import {withNetwork} from '../OnyxProvider';
import {withPersonalDetails} from '../OnyxProvider';
import ReportActionItemSingle from './ReportActionItem/ReportActionItemSingle';
import ReportActionItemImage from './ReportActionItem/ReportActionItemImage';
import ReportActionItemMessage from './ReportActionItem/ReportActionItemMessage';
import {withNetwork} from '../OnyxProvider';
import {withPersonalDetails} from '../OnyxProvider';
import {withReportActionsDrafts} from '../OnyxProvider';
import ReportActionItemFragment from './ReportActionItemFragment';
import ReportActionItemFragment from './ReportActionItemFragment';
import {withNetwork} from '../OnyxProvider';
import {withPersonalDetails} from '../OnyxProvider';
import ReportActionItemFragment from './ReportActionItemFragment';
import {withNetwork} from '../OnyxProvider';
import ReportActionItemFragment from './ReportActionItemFragment';
import ReportActionItemFragment from './ReportActionItemFragment';