                                                    <Text
                                                        numberOfLines={1}
                                                        ellipsizeMode="tail"
                                                        style={[
                                                            styles.textStrong,
                                                            styles.flex1,
                                                            styles.mr2,
                                                        ]}
                                                    >
                                                        {item.name}
                                                    </Text>