// ... existing code ...
const CONST = {
    // ... existing code ...
    REGEX: {
        ALPHABETIC_AND_LATIN_CHARS: /^[\p{L}\s]+$/u,
        // ... existing code ...
    },
    // ... existing code ...
} as const;

export default CONST;