// ... existing code ...
const CONST = {
    // ... existing code ...
    VALIDATION: {
        // ... existing code ...
        CARD_NAME: {
            // ... existing code ...
            PATTERN: /^[a-zA-Z0-9\s]+$/,
            // ... existing code ...
        },
        // ... existing code ...
    // ... existing code ...
};

export default CONST;